#define Py_Initialize ((void(*)(void))imports[0].proc)
#define PyRun_SimpleString ((int(*)(char *))imports[1].proc)
#define Py_Finalize ((void(*)(void))imports[2].proc)
#define Py_GetPath ((char *(*)(void))imports[3].proc)
#define Py_SetPythonHome ((void(*)(char *))imports[4].proc)
#define Py_SetProgramName ((void(*)(char *))imports[5].proc)
#define PyMarshal_ReadObjectFromString ((PyObject *(*)(char *, int))imports[6].proc)
#define PyObject_CallFunction ((PyObject *(*)(PyObject *, char *, ...))imports[7].proc)
#define PyString_AsStringAndSize ((int(*)(PyObject *, char **, int *))imports[8].proc)
#define PyArg_ParseTuple ((int(*)(PyObject *, char *, ...))imports[9].proc)
#define PyErr_Format ((PyObject *(*)(PyObject *, const char *, ...))imports[10].proc)
#define PyImport_ImportModule ((PyObject *(*)(char *))imports[11].proc)
#define PyInt_FromLong ((PyObject *(*)(long))imports[12].proc)
#define PyInt_AsLong ((long(*)(PyObject *))imports[13].proc)
#define PyLong_FromVoidPtr ((PyObject *(*)(void *))imports[14].proc)
#define Py_InitModule4 ((PyObject *(*)(char *, PyMethodDef *, char *, PyObject *, int))imports[15].proc)
#define PyTuple_New ((PyObject *(*)(int))imports[16].proc)
#define PyTuple_SetItem ((int(*)(PyObject*, int, PyObject *))imports[17].proc)
#define Py_IsInitialized ((int(*)(void))imports[18].proc)
#define PyObject_SetAttrString ((int(*)(PyObject *, char *, PyObject *))imports[19].proc)
#define PyCFunction_NewEx ((PyObject *(*)(PyMethodDef *, PyObject *, PyObject *))imports[20].proc)
#define PyObject_GetAttrString ((PyObject *(*)(PyObject *, char *))imports[21].proc)
#define Py_BuildValue ((PyObject *(*)(char *, ...))imports[22].proc)
#define PyObject_Call ((PyObject *(*)(PyObject *, PyObject *, PyObject *))imports[23].proc)
#define PySys_WriteStderr ((void(*)(const char *, ...))imports[24].proc)
#define PyErr_Occurred ((PyObject *(*)(void))imports[25].proc)
#define PyErr_Clear ((void(*)(void))imports[26].proc)
#define PyObject_IsInstance ((int(*)(PyObject *, PyObject *))imports[27].proc)
#define PyInt_Type (*(PyObject(*))imports[28].proc)
#define _Py_NoneStruct (*(PyObject(*))imports[29].proc)
#define PyExc_ImportError (*(PyObject *(*))imports[30].proc)
#define PyGILState_Ensure ((PyGILState_STATE(*)(void))imports[31].proc)
#define PyGILState_Release ((void(*)(PyGILState_STATE))imports[32].proc)
#define PySys_SetObject ((void(*)(char *, PyObject *))imports[33].proc)
#define PySys_GetObject ((PyObject *(*)(char *))imports[34].proc)
#define PyString_FromString ((PyObject *(*)(char *))imports[35].proc)
#define Py_FdIsInteractive ((int(*)(FILE *, char *))imports[36].proc)
#define PyRun_InteractiveLoop ((int(*)(FILE *, char *))imports[37].proc)
#define PySys_SetArgv ((void(*)(int, char **))imports[38].proc)
#define PyImport_AddModule ((PyObject *(*)(char *))imports[39].proc)
#define PyModule_GetDict ((PyObject *(*)(PyObject *))imports[40].proc)
#define PySequence_Length ((int(*)(PyObject *))imports[41].proc)
#define PySequence_GetItem ((PyObject *(*)(PyObject *, int))imports[42].proc)
#define PyEval_EvalCode ((PyObject *(*)(PyCodeObject *, PyObject *, PyObject *))imports[43].proc)
#define PyErr_Print ((void(*)(void))imports[44].proc)
#define PyBool_FromLong ((PyObject *(*)(long))imports[45].proc)
#define Py_VerboseFlag (*(int(*))imports[46].proc)
#define Py_NoSiteFlag (*(int(*))imports[47].proc)
#define Py_OptimizeFlag (*(int(*))imports[48].proc)
